[package]
name = "lestinia-server"
version = "0.1.0"
authors = ["grivo <notgrivo@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "lestinia-common", path = "../common" }
world = { package = "lestinia-world", path = "../world" }

specs = "0.14"
